FROM nginx:alpine

# کپی فایل تنظیمات Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# کپی فایل‌های ساخته‌شده از مرحله build
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]